### ISSUE TITLE
Redesign Authorization Algorithm

### ISSUE THREAD

**Issue by sumdevdotnet** [ahmadirfaan/sdone-ptw#3]
Mungkin idealnya adalah
```
role.[task].allowed=GROUP.permission, GROUP.permission
```

**Comment by sumdevdotnet** [comment]
### Requirements
1. Setiap backend service memiliki 1 logic untuk melakukan otorisasi yang mengecek apakah user yang login memiliki hak untuk mengakses service tersebut.
2. Definisi role yang diperbolehkan untuk mengakses ke dalam service disimpan dalam configuration file.

#### Contoh role definition di dalam sebuah service
```
{
    "roles": [
        {
            "group": "MAINTENANCE",
            "permission": ["operator", "kepala"]
        },
        {
            "group": "OCC",
            "permission": ["operator", "approve"]            
        }
        ]
}
```

#### Contoh configuration file
**role.[service_name].allowed=GROUP.permission, GROUP.permission**

**Comment by ahmadirfaan** [comment]
ini logicnya gimana mas?

misal 

`
config-nya: role.wizard9.allowed=OCC.approve
`
lalu username: ahmadirfaan punya permission

`
{
    "roles": [
        {
            "group": "MAINTENANCE",
            "permission": ["approve"]
        },
        {
            "group": "OCC",
            "permission": ["operator]            
        }
        ]
}
`

ini gimana?? @sumdevdotnet, atau sekalian kasih casenya mas.
biar gk multi persepsi juga ketika buat codingan

**Comment by sumdevdotnet** [comment]
> ini logicnya gimana mas?
> 
> misal
> 
> `config-nya: role.wizard9.allowed=OCC.approve` lalu username: ahmadirfaan punya permission
> 
> `{ "roles": [ { "group": "MAINTENANCE", "permission": ["approve"] }, { "group": "OCC", "permission": ["operator] } ] }`
> 
> ini gimana?? @sumdevdotnet, atau sekalian kasih casenya mas. biar gk multi persepsi juga ketika buat codingan

Di case tersebut ga bisa Mas, karena yang boleh akses wizard9 adalah group OCC permission operator.

Sebenarnya di UML Activity saya selalu mendefinisikan roles apa saja yang dibolehkan mengakses service terkait pada saat dibuat.

<img width="647" alt="image" src="https://github.com/ahmadirfaan/sdone-ptw/assets/128962925/95abbe82-f797-4bb5-8224-7bf18af3c7bf">


Secara konsep, role tersebut bisa dirubah dengan merubah configuration filenya. Tujuannya jika nanti dari user ada requirement baru terkait otorisasi, tinggal dirubah di config file.

**Comment by ahmadirfaan** [comment]
berarti gini kita bakal ngecek for loop untuk roles.

ketika group != yang ada di allowedRoles maka akan ke iterasi selanjutnya.

semisal sama maka akan kita cek apakah punya permission sesuai di allowedRoles.

gini kan ya mas??

**Comment by sumdevdotnet** [comment]
Betul, saya coba elaborasi ya: 

**cek apakah group dan permission milik user yang sedang login ada di dalam allowedRoles di configuration file**

Yang saya belum tau, apakah di configuration file bisa naruh data multi value seperti itu.

**Comment by sumdevdotnet** [comment]
Closed by https://github.com/ahmadirfaan/sdone-ptw/commit/bdd0ff6d052aade1fd7c760e8c637eed5a9b3e5a
