### ISSUE TITLE
Revisi Pre-Condition Pada Saat Edit Data

### ISSUE THREAD

**Issue by sumdevdotnet** [ahmadirfaan/sdone-ptw#8]
Saat ini PTW Pre Duty bisa di-edit jika `Ptw.status == DRAFT || Daily.status == DRAFT`
<img width="280" alt="image" src="https://github.com/ahmadirfaan/sdone-ptw/assets/128962925/b83da556-165f-475f-af0c-02a3d57c8872">

Minta tolong diupdate precondition tersebut, sehingga PTW dengan status DECLINED dapat di-edit.
`PTW.status == DRAFT || PTW.status == DECLINED || DAILY.status == DRAFT`

**Comment by ahmadirfaan** [comment]
btw ini DAILY status kan ada banyak yah, karena per daily mas @sumdevdotnet.

berarti harusnya PTW.status == DRAFT || PTW.status == DECLINED || PtwDailyStatuses.contains(DAILY.status == DRAFT)_

**Comment by sumdevdotnet** [comment]
> btw ini DAILY status kan ada banyak yah, karena per daily mas @sumdevdotnet.
> 
> berarti harusnya PTW.status == DRAFT || PTW.status == DECLINED || PtwDailyStatuses.contains(DAILY.status == DRAFT)_

Concert saat ini di status PTW sih Mas, jadi yang DECLINED bisa di edit. Untuk yang daily belum ada issue dari user, jadi mungkin as is saat ini aja dulu.

Bisa dieksekusi Mas?

**Comment by sumdevdotnet** [comment]
Closed by https://github.com/ahmadirfaan/sdone-ptw/commit/bdd0ff6d052aade1fd7c760e8c637eed5a9b3e5a
